### ISSUE TITLE
Error on message.

### ISSUE THREAD

**Issue by DAVID9SE** [bmintz/reactor-bot#18]
Hey,I installed the requirements without an error and then I ran it using the command.After running the bot it connects to discord and after loading gives:
Ignoring exception in on_ready
Traceback (most recent call last):
  File "/home/kaoirah/.local/lib/python3.6/site-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "/home/kaoirah/reactor-bot-master/reactor_bot/__init__.py", line 28, in on_ready
    await bot.change_presence(activity=discord.Game(name='poll:help'))
TypeError: change_presence() got an unexpected keyword argument 'activity'

after i tried to send a message this results in an error 
Traceback (most recent call last):
  File "/home/kaoirah/.local/lib/python3.6/site-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "/home/kaoirah/reactor-bot-master/reactor_bot/__init__.py", line 41, in on_message
    context = await bot.get_context(message)
  File "/home/kaoirah/.local/lib/python3.6/site-packages/discord/client.py", line 296, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class 'discord.ext.commands.bot.Bot'>' object has no attribute 'get_context'
Thanks

**Comment by DAVID9SE** [comment]
Great, it was just colliding with the old discord .py.Thanks
A venv solved the issue

**Comment by bmintz** [comment]
Feel free to DM me, @lambda#0987 if you have other issues. I wanna know if you get it to work!
